name: Publish Docker Image
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * SAT'
jobs:
  push_to_registries:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: raeffs/verdaccio
          tags: latest
